version: '2'
services:
  applicazioneesempio-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/ApplicazioneEsempio/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ApplicazioneEsempio
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
